//
//  DataClass.h
//  relapps
//
//  Created by Diego Loop on 23/04/16.
//  Copyright © 2016 Herzly. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface Data : NSObject

@property (nonatomic) int ballColor;
@property (nonatomic) int titleColor;
@property (nonatomic) int titleFontSize;
@property (nonatomic, strong) NSMutableDictionary *quotes;

- (NSDictionary *)getRandomQuote;

+ (NSString *) stringFromTimeInterval:(NSTimeInterval)interval;
+ (NSArray *) hourMinSecFromTimeInterval:(NSTimeInterval)interval;
+ (NSString *)sumOfDates:(float)firstDate :(float)secondDate;

// TODO: I don't think it's used
+ (NSArray *) relaxingTimePerDays:(int)days;

+ (BOOL)isRelaxingTimeOverOnDays:(float)days oldDate:(NSDate *)oldDate newDate:(NSDate *)newDate;

+ (float)findRelaxingPercentUsageGoal:(int)goal currentTimeInMin:(float)currentTime;

+ (NSString *)formatDate:(NSDate *)date format:(NSString *)format;

+ (float)scaleFactor:(float)height;

+ (Data *) getInstance;

#define URL_APP @"itms-apps://itunes.apple.com/app/id1158285948"

#define UIColorFromRGB(rgbValue) \
[UIColor colorWithRed:((float)((rgbValue & 0xFF0000) >> 16))/255.0 \
green:((float)((rgbValue & 0x00FF00) >>  8))/255.0 \
blue:((float)((rgbValue & 0x0000FF) >>  0))/255.0 \
alpha:1.0]

#define FONT_FAMILY_THIN @"HelveticaNeue-Thin"

#define MODALVIEW_BACKCOLOR /*0xFFFFFF*/ 0xECECEC
#define MODALVIEW_STROKECOLOR 0xCECECE
#define LINE_SEPARATION_COLOR 0xDCDCDC
#define LIGHT_LINE_SEPARATION_COLOR 0xededed
#define TEXT_COLOR 0x666666
#define TEXT_COLOR_LIGHT 0x959595
#define ILLUSTRATION_CIRCLE_COLOR 0xDDF2EC //0xDEF8B7// 0xCBE59F //0xDDF2EC
#define BACKGROUND_UICOLOR_DEFAULT 0xF5F5F5 // Used in storyboard on uitableviews
#define SHADOW_COLOR 0x8FC9AD

#define ILLUSTRATION_SIZE 300

#define BACKGROUNDSTYLEDEFAULT 0xBAE1CE
#define BACKGROUNDSTYLEWATTERSEE 0x86CFC3
#define BACKGROUNDSTYLEWATTERSEEINVERT 0x86CFC3
#define BACKGROUNDSTYLEMEXICOLAKE 0xACC4CB
#define BACKGROUNDSTYLEBLUEDEMON 0x31A6E1
#define BACKGROUNDSTYLEGREENDEMON 0x80CDAB
#define BACKGROUNDSTYLENIGHT 0x3399D0
#define BACKGROUNDSTYLEPASTELDREAM 0xBAE6E3
#define GREEN_ACCENT_COLOR 0x85CA78

#define BACKGROUND_STATISTICS_COLOR 0xF4F4F4

#define TABBAR_DARK_GREEN_TINT_COLOR 0x719B7C

#define BACKGROUNDSTYLEOPACITY 0.75f

#define LINE_SEPARATION_SIZE 1.0f

#define LIGHT_ALPHA_BACKGROUND 0.15
#define DARK_ALPHA_BACKGROUND 0.60

#define CORNERN_RADIUS 6.0f
#define BIG_CORNER_RADIUS 6.0f

#define SCALE_FACTOR 16.69 // works on all iphone sizes

#define BALLSIZE 100.0f

#define RELAX_WAVE_DURATION_PULSE_SLOW 15.0f
#define RELAX_WAVE_DURATION_PULSE_MEDIUM_DEFAULT 12.0f
#define RELAX_WAVE_DURATION_PULSE_FAST 8.0f

#define RELAX_WAVE_LINEWIDTH 0.4f

#define RELAX_SPEED_BALL_BL 12.0f
#define RELAX_SPEED_BALL_LG 10.0f
#define RELAX_SPEED_BALL_BM 5.0f
#define RELAX_SPEED_BALL_MD 4.0f
#define RELAX_SPEED_BALL_BS 3.0f
#define RELAX_SPEED_BALL_SM 2.0f

#define RELAX_BALL_DURATION_MOVE_DEFAULT 5.0f

#define RELAX_BALL_SPEED_MOVE_SLOW 0.2f
#define RELAX_BALL_SPEED_MOVE_MEDIUM_DEFAULT 0.35f
#define RELAX_BALL_SPEED_MOVE_FAST 0.5f

#define RELAX_BALL_SPEED_MOVE_SETTINGS_INDEX 1

#define RELAX_BREATHE_DURATION_DEFAULT 4.5f

#define RELAX_MINIMUM_MINUTES_GOAL 1
#define RELAX_MAXIMUM_MINUTES_GOAL 20
#define RELAX_MINUTES_GOAL_DEFAULT 3

#define PRESSREDUCTION 0.90f // 10%
#define BREATHEREDUCTION 0.75f

#define OS_TABBAR_HEIGHT 20.0f

#define MIN_MARGIN 20.0f
#define MIN_MARGIN_2X MIN_MARGIN*2

#define BTNSIZE 40.0f
#define BTNSIZE_BIG 45.0f
#define TAB_BUTTON_SIZE 30.0f

#define SEGUE_RELAXVIEW @"ShowRelaxView"
#define SEGUE_HOWTOVIEW @"ShowHowToView"
#define SEGUE_OVERVIEWVIEW @"ShowOverviewView"
#define SEGUE_ABOUT @"ShowAbout"
#define SEGUE_ABOUTCONTENT @"ShowAboutContent"
#define SEGUE_FINDPLACEVIEW @"ShowFindPlaceView"
#define SEGUE_SETTINGS @"ShowSettings"

#define BIGTIMEFRAME 200.0f

#define DATE_FORMATE_MMDDYYYYHHMM @"MMM dd, yyyy, hh:mm p"

#define RELAX_PERIOD_OVER_IN_DAYS 1
#define RELAX_GOAL_PERDAY_IN_MIN 5

#define NUMBER_OF_FAIL_RELAXING_ATTEMS 3


// Settings NSUserDefaults
#define OVERVIEWVIEWCONTROLLER_RELAXMINUTESGOAL @"OVERVIEWVIEWCONTROLLER_RELAXMINUTESGOAL"
#define RELAXVIEW_RELAXBALLSPEEDMOVE @"RELAXVIEW_RELAXBALLSPEEDMOVE"
#define RELAXVIEW_RELAXWAVEDURATIONPULSE @"RELAXVIEW_RELAXWAVEDURATIONPULSE"

#define SETTINGSTABLEVIEWCONTROLLER_RELAXBALLSPEEDMOVEINDEX @"SETTINGSTABLEVIEWCONTROLLER_RELAXBALLSPEEDMOVEINDEX"
#define SETTINGSTABLEVIEWCONTROLLER_RELAXWAVEDURATIONPULSEINDEX @"SETTINGSTABLEVIEWCONTROLLER_RELAXWAVEDURATIONPULSEINDEX"

#define SETTINGS_BALL_SPEED_SEGMENT_DEFAULT 1
#define SETTINGS_WAVE_DURATION_SEGMENT_DEFAULT 1


// Time Things to Track
#define RELAXVIEW_FIRSTRELAXINGDATE @"RELAXVIEW_FIRSTRELAXINGDATE"
#define RELAXVIEW_TOTALRELAXINGDURATIONTIME @"RELAXVIEW_TOTALRELAXINGDURATIONTIME"
#define RELAXVIEW_ONEDAYRELAXINGDATE @"RELAXVIEW_ONEDAYRELAXINGDATE"
#define RELAXVIEW_ONEDAYRELAXINGTIME @"RELAXVIEW_ONEDAYRELAXINGTIME"
#define RELAXVIEW_LASTRELAXINGSESSIONDURATIONTIME @"RELAXVIEW_LASTRELAXINGSESSIONDURATIONTIME"
#define RELAXVIEW_TOTALCOMPLETEDSESSIONS @"RELAXVIEW_TOTALCOMPLETEDSESSIONS"
#define RELAXVIEW_ISTOTALCOMPLETEDSESSIONALREADYADDED @"RELAXVIEW_ISTOTALCOMPLETEDSESSIONALREADYADDED"

// REMINDERS
#define REMINDERVIEWCONTROLLER_DAYSSELECTED @"REMINDERVIEWCONTROLLER_DAYSSELECTED"
#define REMINDERVIEWCONTROLLER_TIMESELECTED @"REMINDERVIEWCONTROLLER_TIMESELECTED"

// ABOUT FEEDBACK
#define EMAIL_FEEDBACK @"DiegoLoop@me.com"

// First time launched
#define IS_APP_ALREADY_LAUNCHED @"IS_APP_ALREADY_LAUNCHED"




@end
